#!/usr/bin/env node

const fs = require('fs');
const rp = require('request-promise');
const cheerio = require('cheerio');
const async = require('async');
const ArgumentParser = require('argparse').ArgumentParser;
const Entities = require('html-entities').AllHtmlEntities;
const pjson = require('./package.json');

var argparser = new ArgumentParser({
    version: pjson.version,
    addHelp:true,
    description: pjson.description
});
argparser.addArgument(
    '-c',
    {
        help: 'Scrape creator\'s theme instead of official\'s',
        action: 'storeFalse'
    }
);
argparser.addArgument(
    '-j',
    {
        help: 'Get .json output instead of .txt',
        action: 'storeTrue'
    }
);
argparser.addArgument(
    '-n',
    {
        help: 'Scrape new category instead of popular',
        action: 'storeFalse'
    }
);
argparser.addArgument(
    '-t',
    {
        help: 'Get spaced & tabbed json instead of single-line one',
        action: 'storeTrue'
    }
);
argparser.addArgument(
    '-f',
    {
        help: 'Get fulll json containing full hyperlink instead of name and ID',
        action: 'storeTrue'
    }
);
args=argparser.parseArgs();

var official = args.c; // true : official || false : creator
var pop = args.n; // true : popular || false : new
var fmt = (args.j)?"json":"txt"; // json or txt formating for output
var tjson = args.t; // true : tabbed json || false : single-line json
var fjson = args.f; // true : full data json || false : short data json
var items_per_q = 1; // items fetched per queue
var failedflag = false;
var failedPages = []; // array of pages that are failed to be fetched
const e = new Entities();
var n = 1; // total themes fetched
var dupe = 0; // total duplicate themes
var ctx = 1; // page loop index
var resp = 200; // initial responseCode
const mxi = (official) ? 10:209; // maximum amount of pages


let str = "\n\tGratter Commence\n\nTheme Target\t: "+
    ((official)?"Official":"Creator")+
    "\nFiletype\t: ."+fmt;
str = (official)? str:str+
    "\nCategory\t: "+ ((pop)?"Popular":"New");
str = (fmt==="json")? str+
    "\nFormatting\t: "+ ((fjson)?"Full + ":"Short + ")+
    ((tjson)?"Tabbed":"Single-Line"):str;
str = str+"\nGranularity\t: "+ items_per_q +" item(s)/queue\n";
console.log(str); 

var url =  (pop)? "https://store.line.me/themeshop/showcase/top_creators/en?page=" :
    "https://store.line.me/themeshop/showcase/new_creators/en?page=";
url = (official)? "https://store.line.me/themeshop/showcase/new/en?page=" : url;
var fn = (pop)? "creators_pop" : "creators_new";
fn = (official)? "officials" : fn;
var l=(fmt=="txt")?'' : {}; 

var q = async.queue(function(task, callback){
    var options = {
        method: 'GET',
        uri: task.url,
        resolveWithFullResponse: true
    };
    rp(options)
    .then(function(response){
        let $ = cheerio.load(response.body);
        $('.mdCMN05Ttl').each(function(){
            cr = (n==1)?'':'\n\n';
            img = $(this).prev().children().attr("src");
            id = (img.length == 127)?img.substr(53,48):img.substr(53,47);
            dl = "http://dl.shop.line.naver.jp/themeshop/v1/products/"+
                   id+"/ANDROID/theme.zip";
            tn = e.decode($(this).html());
            // if(!official && pop) tn=tn.substr((tn.indexOf('.'))+2);
            if(fmt=='txt'){
                    l+=cr+tn+"\n"+dl;
                    n++;
            }else if(fmt=='json'){
                if(l[tn] !== undefined) dupe++;
                else{
                    n++;
                    l[tn] = (!fjson)? id :
                        { "link" : dl,"img" : img };
                }
            }
        });
        callback(task.idx);
    })
    .catch(function(err){
        resp=err.statusCode;
        if(resp==undefined) {
            console.log(err);
            q.kill();
        }
        else{
            process.stdout.write("Error : "+task.url+
                " code : "+resp+"\n");  
        }

        callback(task.idx,resp);
    });
}, items_per_q);

q.drain = function(){
    if(failedflag){
        failedflag = false;
        console.log(`\n\nFailed Pages: ${failedPages.toString()}\nRetrying\n\n`);
        var tmpFailedPages = failedPages;
        failedPages = [];
        for(var loop_i = 0; loop_i<tmpFailedPages.length; loop_i++){
            safePush(tmpFailedPages[loop_i]);
        }
    }
    else{
        const odir = './output/';
        if(!fs.existsSync(odir)) fs.mkdirSync(odir);
        if(fmt=="json"){ 
            l = (tjson)? JSON.stringify(l,null,4) : JSON.stringify(l);
            fn = (fjson)? 'l-'+fn:fn;
        }
        fs.writeFile(odir+fn+"."+fmt, l, function(err){
            if(!err){
                process.stdout.write('\n\nFile successfully written!'+
                    "\nCheck your project directory for the '"+odir+
                    fn+'.'+fmt+"' directory\n");
            }else{
                process.stdout.write("\033[<2>B"+err);
            }
        });
    }
}



function safePush(safe_i){
    q.push({url:url+safe_i, idx: safe_i}, function(x,y){
        process.stdout.write("on page "+x+
            " -> "+ctx+" Pages, "+
            (n-1)+" Themes, "+
            dupe+" Duplicates\r");
        if(y!=undefined){
            failedflag = true;
            failedPages.push(x);
        }else{
            ctx++;
        }
    });
}

for(var i = 1; i <= mxi; i++){
    safePush(i);
}





