#!/usr/bin/env node
const readline = require('readline');
const fs = require('fs');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

var arg1 = (process.argv[2][0] == '.')? process.argv[2] : './'+process.argv[2];
var arg2 = (process.argv[3][0] == '.')? process.argv[3] : './'+process.argv[3];

var fn = 'boilerplate.json';

if(arg1 != undefined && arg2 != undefined){
    

    const j1 = require(arg1);
    const j2 = require(arg2);
    var merged = j1;
    var cmerged = 0;
    var cdupe = 0;

    j2key = Object.keys(j2);
    for(var idx=0, len=j2key.length; idx<len; idx++){
        if(merged[j2key[idx]] != undefined){
            cdupe++;
        }else{
            cmerged++;
            merged[j2key[idx]] = j2[j2key[idx]];
        }
    }

    rl.question('enter merged file name : ', (answer) => {
        fn = answer;

        fs.writeFile('./output/'+fn+'.json', JSON.stringify(merged), function(err){
            if(!err){
                process.stdout.write('\nFile successfully merged!'+
                    '\nCheck your project directory for the \'./output/'+
                    fn+'.json\n');
            }else{
                process.stdout.write('\033[<2>B' + err);
            }
        });
        console.log(`\nMerged\t\t = ${cmerged}\n`+
            `Duplicate\t = ${cdupe}\n`+
            `Total\t\t = ${Object.keys(j1).length}`);
        rl.close();
    });

}

