#!/usr/bin/env node
const readline = require('readline');
const fs = require('fs');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

var arg1 = process.argv[2],
    arg2 = process.argv[3];

var fn = 'tes.json';

if(arg1 != undefined && arg2 != undefined){
    

    const j1 = require(arg1);
    const j2 = require(arg2);
    var merged = j1;

    j2key = Object.keys(j2);
    for(var idx=0, len=j2key.length; idx<len; idx++){
        merged[j2key[idx]] = j2[j2key[idx]];
    }

    rl.question('enter merged file name : ', (answer) => {
        fn = answer;
        console.log('merged file name is : ' + fn);  

        fs.writeFile('./output/'+fn+'.json', JSON.stringify(merged), function(err){
            if(!err){
                process.stdout.write('\n\nFile successfully merged!'+
                    '\nCheck your project directory for the \'./output/'+
                    fn+'\n');
            }else{
                process.stdout.write('\033[<2>B' + err);
            }
        });
        rl.close();
    });

}

