#!/usr/bin/env node

const fs = require('fs');
const rp = require('request-promise');
const cheerio = require('cheerio');
const async = require('async');
const ArgumentParser = require('argparse').ArgumentParser;
const Entities = require('html-entities').AllHtmlEntities;
const pjson = require('./package.json');

var argparser = new ArgumentParser({
    version: pjson.version,
    addHelp:true,
    description: pjson.description
});
argparser.addArgument(
    '-c',
    {
        help: 'Scrape creator\'s theme instead of official\'s',
        action: 'storeFalse'
    }
);
argparser.addArgument(
    '-j',
    {
        help: 'Get .json output instead of .txt',
        action: 'storeTrue'
    }
);
argparser.addArgument(
    '-n',
    {
        help: 'Scrape new category instead of popular',
        action: 'storeFalse'
    }
);
argparser.addArgument(
    '-t',
    {
        help: 'Get spaced & tabbed json instead of single-line one',
        action: 'storeTrue'
    }
);
argparser.addArgument(
    '-f',
    {
        help: 'Get fulll json containing full hyperlink instead of name and ID',
        action: 'storeTrue'
    }
);
args=argparser.parseArgs();

var official = args.c;
var pop = args.n;
var fmt = (args.j)?"json":"txt";
var tjson = args.t;
var fjson = args.f;

let str = "\n\tGratter Commence\n\nTheme Target\t: "+
    ((official)?"Official":"Creator")+
    "\nFiletype\t: ."+fmt;
str = (official)? str:str+
    "\nCategory\t: "+ ((pop)?"Popular":"New");
str = (fmt==="json")? str+
    "\nFormatting\t: "+ ((fjson)?"Full + ":"Short + ")+
    ((tjson)?"Tabbed":"Single-Line"):str;
str = str+"\n";
console.log(str); 

const e = new Entities();
var n = 1; //total themes fetched
var dupe = 0; //total duplicate themes
var i = 1; //page fetched
var resp = 200; //initial responseCode

var url =  (pop)? "https://store.line.me/themeshop/showcase/top_creators/en?page=" :
    "https://store.line.me/themeshop/showcase/new_creators/en?page=";
url = (official)? "https://store.line.me/themeshop/showcase/new/en?page=" : url;
var fn = (pop)? "creators_pop" : "creators_new";
fn = (official)? "officials" : fn;
var l=(fmt=="txt")?'':
    {
        dlink:"http://dl.shop.line.naver.jp/themeshop/v1/products/<THEME_ID>/<DEVICE_PLATFORM>/theme.zip",
        img:{
            a:"https://sdl-shop.line.naver.jp/themeshop/v1/products/<THEME_ID>/ANDROID/en/preview_001_720x1232.png",
            b:"https://sdl-shop.line.naver.jp/themeshop/v1/products/<THEME_ID>/ANDROID/en/preview_002_720x1232.png",
            c:"https://sdl-shop.line.naver.jp/themeshop/v1/products/<THEME_ID>/ANDROID/en/preview_003_720x1232.png",
            d:"https://sdl-shop.line.naver.jp/themeshop/v1/products/<THEME_ID>/ANDROID/en/preview_004_720x1232.png",
            e:"https://sdl-shop.line.naver.jp/themeshop/v1/products/<THEME_ID>/ANDROID/en/preview_005_720x1232.png"
        },
        theme:{}
    }; 

function fetchPage(callback){
    urli = url+i.toString();
    var options = {
        method: 'GET',
        uri: urli,
        resolveWithFullResponse: true
    };
    rp(options)
    .then(function(response){
        let $ = cheerio.load(response.body);
        $('.mdCMN05Ttl').each(function(){
            cr = (n==1)?'':'\n\n';
            img = $(this).prev().children().attr("src");
            id = (img.length == 127)?img.substr(53,48):img.substr(53,47);
            dl = "http://dl.shop.line.naver.jp/themeshop/v1/products/"+
                   id+"/ANDROID/theme.zip";
            tn = e.decode($(this).html());
            if(fmt=='txt'){
                    l+=cr+tn+"\n"+dl;
                    n++;
            }else if(fmt=='json'){
                if(l.theme[tn] !== undefined) dupe++;
                else{
                    n++;
                    l.theme[tn] = (!fjson)? id :
                        { "link" : dl,"img" : img };
                }
            }
        });
        process.stdout.write(i+" Pages, "+
            (n-1)+" Themes, "+
            dupe+" Duplicates\r");
        i++;
        callback();
    })
    .catch(function(err){
        resp=err.statusCode;
        if(resp==undefined) console.log(err);
        else{
            process.stdout.write("\n\n"+urli+
                "\nresponse code : "+resp);  
        }
        callback(err);
    });
}

function writeFile(){
    const odir = './output';
    if(!fs.existsSync(odir)) fs.mkdirSync(odir);
    if(fmt=="json"){ 
        l = (tjson)? JSON.stringify(l,null,4) : JSON.stringify(l);
        fn = (fjson)? 'l-'+fn:fn;
    }
    fs.writeFile("./output/"+fn+"."+fmt, l, function(err){
        if(!err){
            process.stdout.write('\n\nFile successfully written!'+
                '\nCheck your project directory for the \'./output/'+
                fn+'.'+fmt+'\' directory\n');
        }else{
            process.stdout.write("\033[<2>B"+err);
        }
    });
}

async.whilst(
    function(){ 
        return resp==200;
    },
    fetchPage,
    function(err){
        setTimeout(function(){
            writeFile();
        },1000);
    }
);






