#!/usr/bin/env node

var file = process.argv[2];
if(file[0]!='.') file="./"+file;
var a = require(file);
if(a.theme==undefined) console.log(Object.keys(a).length);
else console.log(Object.keys(a.theme).length);
